[package]
name = "tantabus-uci"
version = "3.0.0-dev"
edition = "2021"
default-run = "tantabus-uci"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tantabus = { path = "../engine" }
cozy-chess = "0.3.1"
