[package]
name = "tantabus-fen-to-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cozy-chess = "0.2.0"
tantabus = { path = "../engine" }
rayon = "1.5.1"
